CREATE TABLE player_ratings (
    uuid CHAR(36) PRIMARY KEY,
    gk SMALLINT UNSIGNED,
    cb SMALLINT UNSIGNED,
    lb_rb SMALLINT UNSIGNED,
    lwb_rwb SMALLINT UNSIGNED,
    cdm SMALLINT UNSIGNED,
    cm SMALLINT UNSIGNED,
    lm_rm SMALLINT UNSIGNED,
    cam SMALLINT UNSIGNED,
    cf SMALLINT UNSIGNED,
    lw_rw SMALLINT UNSIGNED,
    st SMALLINT UNSIGNED,
    FOREIGN KEY (uuid) REFERENCES person_info(uuid)
);